# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Civ13
tagline:          ''
description:      'The multiplayer society-building game'
url:              http://civ13.com
baseurl:          /

author:
  name:           'Civilization 13 Team'
  url:            https://github.com/civ13
